### ISSUE TITLE
variable name typo. arguments.bIncludeNonString

### ISSUE THREAD

**Issue by mightaswell** [jeffcoughlin/farcrysolrpro#69]
../packages/types/solrProContentType.cfm line 279

arguments.bInclueNonString

is missing the "d" in Include

**Comment by seancoyne** [comment]
Thanks

**Comment by seancoyne** [comment]
fixed in [v1.3.1](https://github.com/jeffcoughlin/farcrysolrpro/tree/1.3.1)
