### ISSUE TITLE
Add faceting results

### ISSUE THREAD

**Issue by jeffcoughlin** [jeffcoughlin/farcrysolrpro#70]
For custom searches, you'll now be able to do faceted searching.

Example of how it will likely work:
oSolrProContentType = application.fapi.getContentType("solrProContentType");
params = { "fl" = "*,score", "fq" = "", "sort" = "score desc", "facet.field" = [] };
params["facet.field"].append("typename"); // Append as many facet options as desired (see Solr facet docs for more options)
stResults = oSolrProContentType.search(argumentCollection = { q = "*:*", start = 1, rows = 10, params = params });
writedump(var=stResults,abort=true);

**Comment by seancoyne** [comment]
released in v.1.4.0
