### ISSUE TITLE
New content not added to the index when not using publishing workflow

### ISSUE THREAD

**Issue by tHeSmUrF** [jeffcoughlin/farcrysolrpro#73]
As per the discussion at http://discourse.farcrycore.org/t/solr-pro-not-indexing-until-a-resave/520

To make this work a change to line 9 of plugins/farcrysolrpro/packages/events/fcTypes.cfc was required.

Change `arguments.stProperties.bDefaultObject `to `arguments.bSessionOnly eq false`

**Comment by seancoyne** [comment]
We need the default object check otherwise incomplete records could be indexed.  I can't tell you why that change worked for you, but I'll have to investigate before we make that change.

**Comment by seancoyne** [comment]
some notes for later:

CF 10
FarCry 7.1.x and 7.2.x
FC Solr Pro 1.3.2

**Comment by seancoyne** [comment]
Looks like core has the `bAfterSave` argument hard coded to false when it announces the saved event during `createData()`.  This is a change that was made in FarCry 7.

So, we'll need to change the `bAfterSave` check (not the `bDefaultObject` one).  I think you're onto something w/ the `bSessionOnly` check though.  We shouldn't be indexing session only saves since those only live for the user's session.

**Comment by tHeSmUrF** [comment]
Hi Sean,

I think there is a problem with this change. I've left the cflog lines in the /farcrysolrpro/packages/custom/eventHandler.cfc file that I was using during debugging. When I now save records with the bAfterSave check removed I'm seeing every save get added to the index twice.

e.g. this is from creating a new record and hitting save:

"Information","ajp-bio-8012-exec-7","02/10/16","09:51:45","DEVELOP_WI_INTRANET","Saving hbAnnouncement"
"Information","ajp-bio-8012-exec-7","02/10/16","09:51:45","DEVELOP_WI_INTRANET","Now checking record AC0DA600-CF7F-11E5-B554005056A670E2"
"Information","ajp-bio-8012-exec-7","02/10/16","09:51:48","DEVELOP_WI_INTRANET","Adding AC0DA600-CF7F-11E5-B554005056A670E2 record to the index"
"Information","ajp-bio-8012-exec-7","02/10/16","09:51:48","DEVELOP_WI_INTRANET","Saving hbAnnouncement"
"Information","ajp-bio-8012-exec-7","02/10/16","09:51:48","DEVELOP_WI_INTRANET","Now checking record AC0DA600-CF7F-11E5-B554005056A670E2"
"Information","ajp-bio-8012-exec-7","02/10/16","09:51:51","DEVELOP_WI_INTRANET","Adding AC0DA600-CF7F-11E5-B554005056A670E2 record to the index"

When I leave the bAfterSave check but replace bDefaultObject with bSessionOnly the record is only added to the index one time.

Regards
Mark

**Comment by seancoyne** [comment]
I'll check it again tomorrow.

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.5.3&pv=9.2.1&source=email_footer_2]
On Tue, Feb 9, 2016 at 5:56 PM, tHeSmUrF <notifications@github.com> wrote:
Hi Sean,

I think there is a problem with this change. I've left the cflog lines in the
/farcrysolrpro/packages/custom/eventHandler.cfc file that I was using during
debugging. When I now save records with the bAfterSave check removed I'm seeing
every save get added to the index twice.

e.g. this is from creating a new record and hitting save:


"Information","ajp-bio-8012-exec-7","02/10/16","09:51:45","DEVELOP_WI_INTRANET","Saving
hbAnnouncement"

"Information","ajp-bio-8012-exec-7","02/10/16","09:51:45","DEVELOP_WI_INTRANET","Now
checking record AC0DA600-CF7F-11E5-B554005056A670E2"

"Information","ajp-bio-8012-exec-7","02/10/16","09:51:48","DEVELOP_WI_INTRANET","Adding
AC0DA600-CF7F-11E5-B554005056A670E2 record to the index"

"Information","ajp-bio-8012-exec-7","02/10/16","09:51:48","DEVELOP_WI_INTRANET","Saving
hbAnnouncement"

"Information","ajp-bio-8012-exec-7","02/10/16","09:51:48","DEVELOP_WI_INTRANET","Now
checking record AC0DA600-CF7F-11E5-B554005056A670E2"

"Information","ajp-bio-8012-exec-7","02/10/16","09:51:51","DEVELOP_WI_INTRANET","Adding
AC0DA600-CF7F-11E5-B554005056A670E2 record to the index"

When I leave the bAfterSave check but replace bDefaultObject with bSessionOnly
the record is only added to the index one time.

Regards
Mark

—
Reply to this email directly or view it on GitHub
[https://github.com/jeffcoughlin/farcrysolrpro/issues/73#issuecomment-182122367] .[https://github.com/notifications/beacon/AAfJ5ZIh4c13L87jzFFmNCxzrYiMO3D_ks5pimYygaJpZM4HWBeq.gif]

**Comment by tHeSmUrF** [comment]
Thanks Sean.
Just for reference I've attached the modified eventHandler.cfc file I'm using with the additional logging.
[eventHandler.zip](https://github.com/jeffcoughlin/farcrysolrpro/files/123911/eventHandler.zip)

**Comment by seancoyne** [comment]
Thanks. I have a feeling core is broadcasting the event twice. So it may be
a bug in core but perhaps there is a way we can work around it.

Indexing it twice on save isn't a huge issue but is obviously unnecessary.

On Tuesday, February 9, 2016, tHeSmUrF <notifications@github.com> wrote:

> Thanks Sean.
> Just for reference I've attached the modified eventHandler.cfc file I'm
> using with the additional logging.
> eventHandler.zip
> <https://github.com/jeffcoughlin/farcrysolrpro/files/123911/eventHandler.zip>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jeffcoughlin/farcrysolrpro/issues/73#issuecomment-182127292>
> .
>


-- 
Sean Coyne
n42 Designs
sean@n42designs.com
http://www.n42designs.com/
http://about.me/seancoyne

**Comment by seancoyne** [comment]
The problem is, that the core `createData()` method hard codes the `bAfterSave` value to false (which makes sense because `createData()` does not call `afterSave()`)

```cfml
<!--- Announce the save event to listeners --->
<cfset application.fc.lib.events.announce(
    component="fcTypes", 
    eventName="saved",
    typename=getTypeName(),
    oType = this,
    stProperties = arguments.stProperties,
    user = arguments.user,
    auditNote = arguments.auditNote,
    bSessionOnly = false,
    bAfterSave = false,
    bAudit = arguments.bAudit ) />
```

but core is not calling `createData()` when you use a formtools form from the webtop.  It is actually always calling `setData()` (according to the loggging I am seeing).  

See below an example logging record I setup.  You can see the only time core calls `createData()` is for the `farLog` record.  The `dmTout` records all call `setData()`.  These are from generic webtop edit screens.  The first two are `bSessionOnly = true` so they are skipped.  The third is the createData call for the farLog record which is properly passed off to the event handler.  The 4th is a `setData()` call but the `bDefaultObject` property for the record is `true` so it is skipped.  The 5th and 6th are calls to `setData()` but they are identical.  There is no way to differentiate between the two, they both pass two tests (`bSessionOnly`, `bDefaultObject`) but bAfterSave is false for both, so if we only process records that have `bAfterSave = true` then we would miss these records.

```
"02/10/2016","11:23:14","chelsea","Announcing saved event in setData()"
"02/10/2016","11:23:14","chelsea","{""typename"":""dmTout"",""oType"":{},""stProperties"":{""DATETIMELASTUPDATED"":""February, 10 2016 11:23:14 -0500"",""LOCKEDBY"":""farcry_CLIENTUD"",""TYPENAME"":""dmTout"",""LASTUPDATEDBY"":""farcry_CLIENTUD"",""CREATEDBY"":""farcry_CLIENTUD"",""DATETIMECREATED"":""February, 10 2016 11:23:14 -0500"",""BDEFAULTOBJECT"":true,""LOCKED"":true,""teaser"":"""",""linkURL"":"""",""OBJECTID"":""94FB15E0-D012-11E5-AC25080027EA87D4"",""link"":"""",""LABEL"":""(incomplete)"",""title"":"""",""OWNEDBY"":""CDD3B33E-A463-9B75-DC0150D316830765"",""linkLabel"":""""},""user"":""farcry_CLIENTUD"",""auditNote"":""Updated"",""bSessionOnly"":true,""bAfterSave"":""false"",""bAudit"":""0""}"
"02/10/2016","11:23:23","chelsea","Announcing saved event in setData()"
"02/10/2016","11:23:23","chelsea","{""typename"":""dmTout"",""oType"":{},""stProperties"":{""DATETIMELASTUPDATED"":""February, 10 2016 11:23:14 -0500"",""LOCKEDBY"":""farcry_CLIENTUD"",""TYPENAME"":""dmTout"",""LASTUPDATEDBY"":""farcry_CLIENTUD"",""CREATEDBY"":""farcry_CLIENTUD"",""BDEFAULTOBJECT"":true,""DATETIMECREATED"":""February, 10 2016 11:23:14 -0500"",""LOCKED"":true,""teaser"":"""",""linkURL"":"""",""OBJECTID"":""94FB15E0-D012-11E5-AC25080027EA87D4"",""link"":"""",""title"":"""",""LABEL"":""(incomplete)"",""linkLabel"":"""",""OWNEDBY"":""CDD3B33E-A463-9B75-DC0150D316830765""},""user"":""farcry_CLIENTUD"",""auditNote"":""Updated"",""bSessionOnly"":true,""bAfterSave"":""false"",""bAudit"":""0""}"
"02/10/2016","11:23:23","chelsea","Announcing saved event in createData()"
"02/10/2016","11:23:23","chelsea","{""typename"":""farLog"",""oType"":{},""stProperties"":{""DATETIMELASTUPDATED"":""February, 10 2016 11:23:23 -0500"",""LOCKEDBY"":"""",""USERID"":""farcry_CLIENTUD"",""typename"":""farLog"",""NOTES"":""Updated"",""LASTUPDATEDBY"":""farcry_CLIENTUD"",""CREATEDBY"":""farcry_CLIENTUD"",""LOCATION"":"""",""DATETIMECREATED"":""February, 10 2016 11:23:23 -0500"",""EVENT"":""update"",""LOCKED"":0,""OBJECTID"":""9B449520-D012-11E5-AC25080027EA87D4"",""TYPE"":""types"",""OBJECT"":""94FB15E0-D012-11E5-AC25080027EA87D4"",""USER"":""anonymous"",""IPADDRESS"":""127.0.0.1""},""user"":""farcry_CLIENTUD"",""auditNote"":""Created"",""bSessionOnly"":false,""bAfterSave"":false,""bAudit"":false}"
"02/10/2016","11:23:23","chelsea","Running the after save event handler"
"02/10/2016","11:23:23","chelsea","Announcing saved event in setData()"
"02/10/2016","11:23:23","chelsea","{""typename"":""dmTout"",""oType"":{},""stProperties"":{""DATETIMELASTUPDATED"":""February, 10 2016 11:23:23 -0500"",""LOCKEDBY"":""farcry_CLIENTUD"",""typename"":""dmTout"",""LASTUPDATEDBY"":""farcry_CLIENTUD"",""CREATEDBY"":""farcry_CLIENTUD"",""DATETIMECREATED"":""February, 10 2016 11:23:14 -0500"",""BDEFAULTOBJECT"":true,""LOCKED"":true,""teaser"":""test 7"",""linkURL"":"""",""ObjectID"":""94FB15E0-D012-11E5-AC25080027EA87D4"",""link"":"""",""LABEL"":""test 7"",""title"":""test 7"",""OWNEDBY"":""CDD3B33E-A463-9B75-DC0150D316830765"",""linkLabel"":""""},""user"":true,""auditNote"":""Updated"",""bSessionOnly"":""false"",""bAfterSave"":true,""bAudit"":""1""}"
"02/10/2016","11:23:23","chelsea","Announcing saved event in setData()"
"02/10/2016","11:23:23","chelsea","{""typename"":""dmTout"",""oType"":{},""stProperties"":{""LOCKEDBY"":"""",""TYPENAME"":""dmTout"",""LOCKED"":""false"",""OBJECTID"":""94FB15E0-D012-11E5-AC25080027EA87D4""},""user"":""farcry_CLIENTUD"",""auditNote"":""Updated"",""bSessionOnly"":false,""bAfterSave"":""false"",""bAudit"":""0""}"
"02/10/2016","11:23:23","chelsea","Running the after save event handler"
"02/10/2016","11:23:24","chelsea","Announcing saved event in setData()"
"02/10/2016","11:23:24","chelsea","{""typename"":""dmTout"",""oType"":{},""stProperties"":{""LOCKEDBY"":"""",""TYPENAME"":""dmTout"",""LOCKED"":false,""OBJECTID"":""94FB15E0-D012-11E5-AC25080027EA87D4""},""user"":""farcry_CLIENTUD"",""auditNote"":""Updated"",""bSessionOnly"":false,""bAfterSave"":""false"",""bAudit"":""0""}"
"02/10/2016","11:23:24","chelsea","Running the after save event handler"
```

So core seems to be to blame here.  They are making apparently identical calls to `setData()` and the plugin is responding to the broadcast events appropriately.

If we were to change it to look for `bAfterSave` then people manually calling `createData()` would not have their records indexed.  We need to handle those records and, unfortunately, unless a change is made to core so that it uses `createData()` and `setData()` where appropriate instead of using `setData()` for both creation and updating or only calls `setData()` once per save we are stuck w/ the current situation.

Your change may work for you while using the webtop forms, but try calling `createData()` to create a record on your own and I think you'll find that your new record is not added to the index.
